Criacao sala
jaacksonalves/stop pull request #1
Opened 2022-03-30 00:11 UTC by jaacksonalves

2022-03-30 13:54 UTC, jaacksonalves commented on .jpb/persistence-units.xml
> +<?xml version="1.0" encoding="UTF-8"?>
vazou um arquivo de um plugin kkk vou tirar.

2022-03-30 14:06 UTC, jaacksonalves commented on src/main/java/br/com/jackson/stop/compartilhado/anotacoes/LetrasCompativeisRodadas.java
> +  String message() default "A quantidade de letras deve ser maior ou igual ao número de rodadas";
feito

2022-03-30 14:11 UTC, jaacksonalves commented on src/main/java/br/com/jackson/stop/compartilhado/anotacoes/LetrasCompativeisRodadasValidator.java
> +    return request.letrasCompativeisComRodadas();
:)

2022-03-30 15:14 UTC, jaacksonalves commented on src/test/java/br/com/jackson/stop/sala/SalaTest.java
> +class SalaTest {
gosto de cobrir de todas as formas, mas faz sentido na questão do tempo e energia gasta.

2022-03-30 15:15 UTC, jaacksonalves commented on src/test/java/br/com/jackson/stop/sala/NovaSalaRequestTest.java
> +  class MetodoLetrasCompativeisComRodadasJqwikTest {
Tive que criar dessa forma pq o JQWIK não funciona dentro de anotações do Junit, como Test ou Nested, dai tive que por numa outra.

2022-03-30 15:15 UTC, jaacksonalves commented on src/main/java/br/com/jackson/stop/sala/Sala.java
> +    this.senha = senha;
pensei nisso antes quando tava na cama pra dormir kkkkkkkk só que deu preguiça de levantar pra arrumar, feito.

2022-03-30 15:16 UTC, jaacksonalves commented on src/main/java/br/com/jackson/stop/sala/NovaSalaRequest.java
> +    // var listaCategorias =
resolvido

2022-03-30 19:41 UTC, jaacksonalves commented on src/main/java/br/com/jackson/stop/compartilhado/handler/ExceptionsHandler.java
> +    var invalidFormat = (InvalidFormatException) exception.getCause();
os testes deram certo kkk

2022-03-31 18:56 UTC, asouza requested changes
Acho que é só alterar o que comentei e mergear

2022-03-31 18:56 UTC, asouza commented on src/main/java/br/com/jackson/stop/compartilhado/handler/ExceptionsHandler.java
> +    var list1 = new ArrayList<String>();
Precsa de um nome de variável com significado aqui

2022-03-31 18:56 UTC, asouza commented on src/main/java/br/com/jackson/stop/compartilhado/handler/ExceptionsHandler.java
>      var map = new HashMap<String, List<String>>();
Precsa de um nome de variável com significado aqui

2022-03-31 19:04 UTC, merged